### PR TITLE
shave some bytes

### PR DESCRIPTION
**Pull request by peterferrie**

### CODE REVIEW

**Review by NieDzejkob — COMMENTED** [review]
Thanks!

**Comment by NieDzejkob** [comment]
So, uhm. This is embarassing. This change doesn't actually work – pressing backspace will replace the last character with a `\x08`, instead of deleting it. Not sure how I missed this...

I reverted the buggy change. If you can see how to fix this bug while still saving some bytes, I'll gladly hear about it! ;)

**Comment by peterferrie** [comment]
> So, uhm. This is embarassing. This change doesn't actually work – pressing
> backspace will replace the last character with a `\x08`, instead of deleting
> it. Not sure how I missed this...

I don't see this behaviour in my side-by-side test.
I stepped through with a debugger, and my code does exactly what the
original code does.
I did not alter any of the input/display code, in any case.
What are you using for tests?  I used DOSBox and VirtualBox.

**Comment by NieDzejkob** [comment]
Try doing the following:
```
123<backspace> u.<enter>
```
On `master`, this prints `12`. On `master^`, with your code, it prints `F1`. The input buffer then looks as follows:
```
(qemu) x/8cb 0x500
00000500: '1' '2' '\x08' ' ' 'u' '.' '\x00' '\x00'
```

**Comment by peterferrie** [comment]
> Try doing the following:
> ```
> 123<backspace> u.<enter>
> ```
> On `master`, this prints `12`. On `master^`, with your code, it prints `F1`.
> The input buffer then looks as follows:
> ```
> (qemu) x/8cb 0x500
> 00000500: '1' '2' '\x08' ' ' 'u' '.' '\x00' '\x00'
> ```

I still don't see it on my side.
The \x08 isn't possible to emit.  The "backspace pressed?" line prevents it.
Did you build my source, or use the binary that's in the PR?
If you built it, does it match the binary?

**Comment by NieDzejkob** [comment]
There aren't any binaries in the PR, as the build artifacts are listed in `.gitignore`. I built your commit and got the following binary:
```
[nix-shell:~/dev/miniforth]$ xxd boot.bin
00000000: ea0d 7c00 00a6 7ccd 7c8f 7c62 7c0e 0e0e  ..|...|.|.|b|...
00000010: 1f07 17bc 057c fcbe eb7c bff2 7db9 0701  .....|...|..}...
00000020: acaa 3cff 750b 4fb8 adff abb0 e0aa e8a7  ..<.u.O.........
00000030: 00e2 ed88 558c 52bf 0005 893e 020a b400  ....U.R....>....
00000040: cd16 3c08 7507 81ff 0005 74f2 4fe8 9000  ..<.u.....t.O...
00000050: aa3c 0d75 e9b0 0acd 1088 5dff e84f 00e3  .<.u......]..O..
00000060: d6be 0000 ad50 ac30 c8a8 5f75 0889 d751  .....P.0.._u...Q
00000070: f3a6 5974 185e 09f6 75ea 5338 268f 7c75  ..Yt.^..u.S8&.|u
00000080: dbb8 fa7d e81e 0058 e81a 00eb cf5b 0c01  ...}...X.....[..
00000090: 9674 f5bf 000b 5bbe 9c7c ffe0 9e7c 893e  .t....[..|...|.>
000000a0: 947c 53eb b7a3 4d7f 8306 a67c 02c3 8b36  .|S...M....|...6
000000b0: 020a 89f2 ac3c 2074 f931 c931 db24 df74  .....< t.1.1.$.t
000000c0: ec41 2c10 3c09 7602 2c27 9869 db10 0001  .A,.<.v.,'.i....
000000d0: c389 3602 0aac ebe5 89f8 8706 627c abc3  ..6.........b|..
000000e0: 31db b40e cd10 c310 0002 0096 ab5e ff53  1............^.S
000000f0: ad93 ff4f 4f8b 35ff 012b 5801 c3ff 012d  ...OO.5..+X....-
00000100: 5829 d893 ff01 408b 1fff 0121 8f07 5bff  X)....@....!..[.
00000110: 0263 400f b61f ff02 6321 5888 075b ff03  .c@.....c!X..[..
00000120: 6475 7053 ff04 6472 6f70 5bff 0473 7761  dupS..drop[..swa
00000130: 7058 5393 ff02 3e72 93ab 5bff 0272 3e4f  pXS...>r..[..r>O
00000140: 4f53 8b1d ff04 656d 6974 93e8 53fe 5bff  OS....emit..S.[.
00000150: 0275 2e93 6af0 31d2 f736 cd7c 5209 c075  .u..j.1..6.|R..u
00000160: f558 0430 3c39 7602 0407 e830 fe3c 2075  .X.0<9v....0.< u
00000170: f05b ff04 6c6f 6164 60bf eb7c b800 06a3  .[..load`..|....
00000180: 020a ab31 c0ab d1e3 93ab 93ab abab a200  ...1............
00000190: 0ab2 00b4 42be e77c cd13 72fe 615b ff02  ....B..|..r.a[..
000001a0: 733a 8736 020a ac88 0743 08c0 75f8 4b4e  s:.6.....C..u.KN
000001b0: 8736 020a ff81 5bfe 068f 7cff 015d fe0e  .6....[...|..]..
000001c0: 8f7c ff01 3a60 8b3e a67c e8b4 fde8 87fd  .|..:`.>.|......
000001d0: 89c8 aa89 d6f3 a4b0 e8aa b8f0 7d29 f8ab  ............})..
000001e0: 893e a67c 61eb d3ff 813b b802 7ee8 5afd  .>.|a....;..~.Z.
000001f0: ebb9 0000 0000 0000 0000 0000 0000 55aa  ..............U.

[nix-shell:~/dev/miniforth]$ sha1sum boot.bin
0d917d9cfc6e8ea800d3de29658d99d102691545  boot.bin
```

I don't exactly understand what you mean by "the backspace pressed? line", there aren't any lines with that comment.

Something weird is going on on your side. There must be a bug in the code, because when backspace is pressed, `di` first gets decremented at `dec di`, and then incremented again at `stosb`, resulting in a delta of 0. Previously this delta was -1.

Make sure you're not doing `1 load` before performing the test — that loads a separate input routine written in Forth.

**Comment by peterferrie** [comment]
Ah, yes my fault.  I'm looking at the wrong FORTH project entirely.
My apologies.  I will review my PR.

**Comment by peterferrie** [comment]
Backspace is fixed in the new PR.

**Pull request merged**
